Traceback (most recent call last):
  File "NNKeras.py", line 125, in <module>
    clf.fit(X_input, y_input)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/model_selection/_search.py", line 553, in _fit
    cv_iter = list(cv.split(X, y, groups))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/model_selection/_split.py", line 322, in split
    for train, test in super(_BaseKFold, self).split(X, y, groups):
  File "/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/model_selection/_split.py", line 90, in split
    indices = np.arange(_num_samples(X))
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'



Par curiosité:
2017-12-12 15:38:21.397671: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-12 15:38:21.423240: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2017-12-12 15:38:21.423364: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (DSL1): /proc/driver/nvidia/version does not exist